// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1vJtVBzOefULsSN-715lrXIU-2R8x7eU',
    appId: '1:880294986559:web:e3f0dcb9b06f69457c498a',
    messagingSenderId: '880294986559',
    projectId: 'gym-tracker-3334e',
    authDomain: 'gym-tracker-3334e.firebaseapp.com',
    storageBucket: 'gym-tracker-3334e.firebasestorage.app',
    measurementId: 'G-C7TKE1V2SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsZAeAjQHWG1hyuIFq7tn1GdKsQIFJPps',
    appId: '1:880294986559:android:283d84b3268f01e37c498a',
    messagingSenderId: '880294986559',
    projectId: 'gym-tracker-3334e',
    storageBucket: 'gym-tracker-3334e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKSt3y8X0oWr_78rkw8q2HC6AXMDGTCZc',
    appId: '1:880294986559:ios:29e5c57ea5bc8c407c498a',
    messagingSenderId: '880294986559',
    projectId: 'gym-tracker-3334e',
    storageBucket: 'gym-tracker-3334e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKSt3y8X0oWr_78rkw8q2HC6AXMDGTCZc',
    appId: '1:880294986559:ios:29e5c57ea5bc8c407c498a',
    messagingSenderId: '880294986559',
    projectId: 'gym-tracker-3334e',
    storageBucket: 'gym-tracker-3334e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1vJtVBzOefULsSN-715lrXIU-2R8x7eU',
    appId: '1:880294986559:web:9179801b90fe9a237c498a',
    messagingSenderId: '880294986559',
    projectId: 'gym-tracker-3334e',
    authDomain: 'gym-tracker-3334e.firebaseapp.com',
    storageBucket: 'gym-tracker-3334e.firebasestorage.app',
    measurementId: 'G-Z56KRSTZBW',
  );
}
